"""Machine-readable orchestration primitives for publication figure workflows."""

from .contracts import (
    BindingMap,
    ComponentSpec,
    ExportManifest,
    LayoutSpec,
    QAReport,
    ReferenceSet,
    RenderPlan,
    SourceSpec,
    ScientificContract,
    PaletteSpec,
    StyleSpec,
    TargetSpec,
    TaskSpec,
    TypographySpec,
)
from .reference_intelligence import (
    DesignPacket,
    DesignPatch,
    JournalProfile,
    PreferencePair,
    ReferenceDNA,
    RenderTrace,
    StyleCapsule,
)
from .orchestrator import (
    GateResult,
    Orchestrator,
    StageArtifact,
    StageContext,
    StageRecord,
    WorkflowSession,
    WorkflowStage,
)

__all__ = [
    "BindingMap",
    "ComponentSpec",
    "ExportManifest",
    "GateResult",
    "LayoutSpec",
    "Orchestrator",
    "QAReport",
    "ReferenceSet",
    "RenderPlan",
    "SourceSpec",
    "ScientificContract",
    "PaletteSpec",
    "StageArtifact",
    "StageContext",
    "StageRecord",
    "StyleSpec",
    "TargetSpec",
    "TaskSpec",
    "TypographySpec",
    "WorkflowSession",
    "WorkflowStage",
    "DesignPacket",
    "DesignPatch",
    "JournalProfile",
    "PreferencePair",
    "ReferenceDNA",
    "RenderTrace",
    "StyleCapsule",
]
